server:
  port: 33780
  address: localhost

spring:
  application:
    name: graphfs
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: graphinjuk

logging:
  level:
    org.springframework.data.neo4j: DEBUG